export const projectViews = [
  {
    name: 'Project single line summary',
    description: 'Project single line summary.',
    component: 'ProjectListWidget',
    fullWidth: true,
    type: 'PortfolioDashboard',
  },
  // {
  //   name: 'Project single line summary New',
  //   description: 'Project Single Line Summary New.',
  //   component: 'ProjectListWidgetNew',
  //   fullWidth: true,
  //   type: 'PortfolioDashboard',
  // },
  {
    name: 'Aged AR trend',
    description:
      'Aged AR trend.',
    component: 'AgedARWidget',
    fullWidth: false,
    type: 'PortfolioDashboard',
  },
  {
    name: 'Billing & AR detail report',
    description:
      'Billing & AR detail report.',
    component: 'BilledARWidget',
    fullWidth: false,
    type: 'PortfolioDashboard',
  },
  {
    name: 'Aged unbilled trend',
    description: 'Aged unbilled trend.',
    component: 'UnbilledARWidget',
    fullWidth: false,
    type: 'PortfolioDashboard',
  },
  {
    name: 'Net receivables',
    description: 'Net receivables.',
    component: 'NetReceivableWidget',
    fullWidth: false,
    type: 'PortfolioDashboard',
  },
  {
    name: 'Profit & loss',
    description: 'Profit & loss.',
    component: 'ProfitLossTable',
    fullWidth: false,
    type: 'PortfolioDashboard',
  },
  {
    name: 'Pending project approvals',
    description: 'Pending project approvals.',
    component: 'PendingProjectApprovalWidget',
    fullWidth: false,
    type: 'PortfolioDashboard',
  },
  {
    name: 'Documents',
    description: 'Documents.',
    component: 'Documents',
    fullWidth: false,
    type: 'PortfolioDashboard',
  },
  {
    name: 'Commitments detail PO status',
    description: 'Commitments detail PO Status.',
    component: 'CommitmentsDtlPoWidget',
    fullWidth: false,
    type: 'PortfolioDashboard',
  },
  {
    name: 'Supplier invoices',
    description: 'Supplier invoices.',
    component: 'VendorInvoicesWidget',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Trend analysis',
    description: 'Trend analysis.',
    component: 'TrendAnalysis',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Pending project approvals',
    description: 'Pending project approvals.',
    component: 'PendingProjectApprovalWidget',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Documents',
    description: 'Documents.',
    component: 'Documents',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Single line data export',
    description: 'Single line data export.',
    component: 'SingleProjectListWidget',
    fullWidth: true,
    type: 'PortfolioDashboard',
  },
  {
    name: 'This week cost',
    description: 'Week cost widget.',
    component: 'ProjWeekCostWidget',
    fullWidth: true,
    type: 'ProjectDashboard',
  },
  {
    name: 'Aged AR trend',
    description:
      'Aged AR trend.',
    component: 'ProjAgedARWidget',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Billing & AR detail report',
    description:
      'Billing & AR detail report.',
    component: 'ProjBilledARWidget',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Aged unbilled trend',
    description: 'Aged unbilled trend.',
    component: 'ProjUnbilledARWidget',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Net receivables',
    description: 'Net receivables.',
    component: 'ProjNetReceivableWidget',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Profit & loss',
    description: 'Profit & loss.',
    component: 'ProfitLossTable',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Trend analysis',
    description: 'Trend analysis.',
    component: 'TrendAnalysis',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Earned value',
    description: 'Earned value.',
    component: 'EarnedValue',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Key performance indicators',
    description: 'Key performance indicators.',
    component: 'KeyPerformanceIndicators',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
]

export const portfolioViews = [
  {
    name: 'Project single line summary',
    description: 'Project single line summary.',
    component: 'ProjectListWidget',
    fullWidth: true,
    type: 'PortfolioDashboard',
  },
  {
    name: 'Aged AR trend',
    description:
      'Aged AR trend.',
    component: 'AgedARWidget',
    fullWidth: false,
    type: 'PortfolioDashboard',
  },
  {
    name: 'Billing & AR detail report',
    description:
      'Billing & AR detail report.',
    component: 'BilledARWidget',
    fullWidth: false,
    type: 'PortfolioDashboard',
  },
  {
    name: 'Aged unbilled trend',
    description: 'Aged unbilled trend.',
    component: 'UnbilledARWidget',
    fullWidth: false,
    type: 'PortfolioDashboard',
  },
  {
    name: 'Net receivables',
    description: 'Net receivables.',
    component: 'NetReceivableWidget',
    fullWidth: false,
    type: 'PortfolioDashboard',
  },
  {
    name: 'Profit & loss',
    description: 'Profit & loss.',
    component: 'ProfitLossTable',
    fullWidth: false,
    type: 'PortfolioDashboard',
  },
  {
    name: 'Pending project approvals',
    description: 'Pending project approvals.',
    component: 'PendingProjectApprovalWidget',
    fullWidth: false,
    type: 'PortfolioDashboard',
  },
  {
    name: 'Documents',
    description: 'Documents.',
    component: 'Documents',
    fullWidth: false,
    type: 'PortfolioDashboard',
  },
  {
    name: 'Commitments detail PO status',
    description: 'Commitments detail PO Status.',
    component: 'CommitmentsDtlPoWidget',
    fullWidth: false,
    type: 'PortfolioDashboard',
  },
  {
    name: 'Supplier invoices',
    description: 'Supplier invoices.',
    component: VendorInvoicesWidget,
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Trend analysis',
    description: 'Trend analysis.',
    component: 'TrendAnalysis',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Single line data export',
    description: 'Single line data export.',
    component: 'SingleProjectListWidget',
    fullWidth: true,
    type: 'PortfolioDashboard',
  },
  {
    name: 'This week cost',
    description: 'Week cost widget.',
    component: 'ProjWeekCostWidget',
    fullWidth: true,
    type: 'ProjectDashboard',
  },
  {
    name: 'Aged AR trend',
    description:
      'Aged AR trend.',
    component: 'ProjAgedARWidget',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Billing & AR detail report',
    description:
      'Billing & AR detail report.',
    component: 'ProjBilledARWidget',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Aged unbilled trend',
    description: 'Aged unbilled trend.',
    component: 'ProjUnbilledARWidget',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Net receivables',
    description: 'Net receivables.',
    component: 'ProjNetReceivableWidget',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Profit & loss',
    description: 'Profit & loss.',
    component: 'ProfitLossTable',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Trend analysis',
    description: 'Trend analysis.',
    component: 'TrendAnalysis',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Earned value',
    description: 'Earned value.',
    component: 'EarnedValue',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Key performance indicators',
    description: 'Key performance indicators.',
    component: 'KeyPerformanceIndicators',
    fullWidth: false,
    type: 'ProjectDashboard',
  },
  {
    name: 'Project fields',
    description: 'List of project fields, formulas, and values.',
    component: 'FormulasWidget',
    fullWidth: true,
    type: 'ProjectDashboard',
  },
]
