export const metricsRows = [
    {
      row: "Gross revenue",
      description: "Total revenue to AECOM",
      prior_period_mtd: "gr_prior_period_mtd",
      mtd: "gr_mtd",
      ytd: "gr_ytd",
      itd: "gr_itd",
      original: "gr_original",
      approved: "gr_approved",
      forecast: "gr_forecast",
      prior_period_forecast: "gr_prior_period_forecast",
      etc: "gr_etc",
      complete: "gr_complete",
      colType: "currencyConversionColumn",
      dynamicCss:'textBold'
    },
    {
      row: "Subs cost",
      description: "Subcontractor and subconsultants cost",
      prior_period_mtd: "subs_prior_period_mtd",
      mtd: "subs_mtd",
      ytd: "subs_ytd",
      itd: "subs_itd",
      original: "subs_original",
      approved: "subs_approved",
      forecast: "subs_forecast",
      prior_period_forecast: "subs_prior_period_forecast",
      etc: "subs_etc",
      complete: "subs_complete",
      colType: "currencyConversionColumn",
      dynamicCss:'leftalign'
    },
    {
      row: "Other direct cost",
      description: "Other direct costs (excluding subcontracts and subconsultants)",
      prior_period_mtd: "odc_prior_period_mtd",
      mtd: "odc_mtd",
      ytd: "odc_ytd",
      itd: "odc_itd",
      original: "odc_original",
      approved: "odc_approved",
      forecast: "odc_forecast",
      prior_period_forecast: "odc_prior_period_forecast",
      etc: "odc_etc",
      complete: "odc_complete",
      colType: "currencyConversionColumn",
      dynamicCss:'leftalign'
    },
    {
      row: "Contingency budget",
      description: "Allocated contingency (budget item only)",
      prior_period_mtd: "cb_prior_period_mtd",
      mtd: "cb_mtd",
      ytd: "cb_ytd",
      itd: "cb_itd",
      original: "cb_original",
      approved: "cb_approved",
      forecast: "cb_forecast",
      prior_period_forecast: "cb_prior_period_forecast",
      etc: "cb_etc",
      complete: "cb_complete",
      colType: "currencyConversionColumn",
      dynamicCss:'leftalign'
    },
    {
      row: "Total other direct cost",
      description: "Subs + Other direct costs + Contingency budget",
      prior_period_mtd: "tod_prior_period_mtd",
      mtd: "tod_mtd",
      ytd: "tod_ytd",
      itd: "tod_itd",
      original: "tod_original",
      approved: "tod_approved",
      forecast: "tod_forecast",
      prior_period_forecast: "tod_prior_period_forecast",
      etc: "tod_etc",
      complete: "tod_complete",
      colType: "currencyConversionColumn",
      dynamicCss:'leftalign'
    },
    {
      type: "hidden",
      row: "Net service revenue (NSR)",
      description: "Net revenue to AECOM: Gross revenue - (Subs + Other direct cost + contingency budget)",
      prior_period_mtd: "nsr_prior_period_mtd",
      mtd: "nsr_mtd",
      ytd: "nsr_ytd",
      itd: "nsr_itd",
      original: "nsr_original",
      approved: "nsr_approved",
      forecast: "nsr_forecast",
      prior_period_forecast: "nsr_prior_period_forecast",
      etc: "nsr_etc",
      complete: "nsr_complete",
      colType: "currencyConversionColumn",
      dynamicCss:'textBold'
    },
    {
      row: "Direct labor cost",
      description: "Direct (raw) labor cost for employee hours",
      prior_period_mtd: "dls_prior_period_mtd",
      mtd: "dls_mtd",
      ytd: "dls_ytd",
      itd: "dls_itd",
      original: "dls_original",
      approved: "dls_approved",
      forecast: "dls_forecast",
      prior_period_forecast: "dls_prior_period_forecast",
      etc: "dls_etc",
      complete: "dls_complete",
      colType: "currencyConversionColumn",
      dynamicCss:'leftalign'
    },
    {
      row: "Fringe cost",
      description: "Fringe cost (applied based on direct labor cost)",
      prior_period_mtd: "fringe_prior_period_mtd",
      mtd: "fringe_mtd",
      ytd: "fringe_ytd",
      itd: "fringe_itd",
      original: "fringe_original",
      approved: "fringe_approved",
      forecast: "fringe_forecast",
      prior_period_forecast: "fringe_prior_period_forecast",
      etc: "fringe_etc",
      complete: "fringe_complete",
      colType: "currencyConversionColumn",
      dynamicCss:'leftalign'
    },
    {
      type: "hidden",
      row: "Gross margin",
      description: "Net Service Revenue - (Direct labor cost + Fringe cost)",
      prior_period_mtd: "gm_prior_period_mtd",
      mtd: "gm_mtd",
      ytd: "gm_ytd",
      itd: "gm_itd",
      original: "gm_original",
      approved: "gm_approved",
      forecast: "gm_forecast",
      prior_period_forecast: "gm_prior_period_forecast",
      etc: "gm_etc",
      complete: "gm_complete",
      colType: "currencyConversionColumn",
      dynamicCss:'textBold'
    },
    {
      row: "Applied overhead",
      description: "Overhead cost (applied based on direct labor cost)",
      prior_period_mtd: "ao_prior_period_mtd",
      mtd: "ao_mtd",
      ytd: "ao_ytd",
      itd: "ao_itd",
      original: "ao_original",
      approved: "ao_approved",
      forecast: "ao_forecast",
      prior_period_forecast: "ao_prior_period_forecast",
      etc: "ao_etc",
      complete: "ao_complete",
      colType: "currencyConversionColumn",
      dynamicCss:'leftalign'
    },
    {
      row: "Fully burdened labor",
      description: "Direct labor cost + Fringe cost + Applied Overhead",
      prior_period_mtd: "fbl_prior_period_mtd",
      mtd: "fbl_mtd",
      ytd: "fbl_ytd",
      itd: "fbl_itd",
      original: "fbl_original",
      approved: "fbl_approved",
      forecast: "fbl_forecast",
      prior_period_forecast: "fbl_prior_period_forecast",
      etc: "fbl_etc",
      complete: "fbl_complete",
      colType: "currencyConversionColumn",
      dynamicCss:'leftalign'
    },
    {
      type: "hidden",
      row: "Total costs",
      description: "Fully burdened labor + Total other direct cost",
      prior_period_mtd: "total_costs_prior_period_mtd",
      mtd: "total_costs_mtd",
      ytd: "total_costs_ytd",
      itd: "total_costs_itd",
      original: "total_costs_original",
      approved: "total_costs_approved",
      forecast: "total_costs_forecast",
      prior_period_forecast: "total_costs_prior_period_forecast",
      etc: "total_costs_etc",
      complete: "total_costs_complete",
      colType: "currencyConversionColumn",
      dynamicCss:'textBold'
    },
    {
      type: "hidden",
      row: "Net margin",
      description: "Gross revenue - Labor - Fringe - Overhead - Subs - Other direct cost - Contingency",
      prior_period_mtd: "nm_prior_period_mtd",
      mtd: "nm_mtd",
      ytd: "nm_ytd",
      itd: "nm_itd",
      original: "nm_original",
      approved: "nm_approved",
      forecast: "nm_forecast",
      prior_period_forecast: "nm_prior_period_forecast",
      etc: "nm_etc",
      complete: "nm_complete",
      colType: "currencyConversionColumn",
      dynamicCss:'textBold'
    },
    {
      row: "Billed (ex Tax)",
      description: "Total billed balance (including retention)",
      prior_period_mtd: "billed_prior_period_mtd",
      mtd: "billed_mtd",
      ytd: "billed_ytd",
      itd: "billed_itd",
      // original: "billed_original",
      // approved: "billed_approved",
      // forecast: "billed_forecast",
      // prior_period_forecast: "billed_prior_period_forecast",
      // etc: "billed_etc",
      // complete: "billed_complete",
      colType: "currencyConversionColumn"
    },
    {
      row: "Cash applications",
      description: "Cash applications applied during the period",
      type: "hidden",
      prior_period_mtd: "ca_prior_period_mtd",
      mtd: "ca_mtd",
      ytd: "ca_ytd",
      itd: "ca_itd",
      // original: "ca_original",
      // approved: "ca_approved",
      // forecast: "ca_forecast",
      // prior_period_forecast: "ca_prior_period_forecast",
      // etc: "ca_etc",
      // complete: "ca_complete",
      colType: "currencyConversionColumn"
    },
    {   
  
      row: "Gross margin % NSR",
      description: "Gross margin / Net Service Revenue",
      prior_period_mtd: "gmn_prior_period_mtd",
      mtd: "gmn_mtd",
      ytd: "gmn_ytd",
      itd: "gmn_itd",
      original: "gmn_original",
      approved: "gmn_approved",
      forecast: "gmn_forecast",
      prior_period_forecast: "gmn_prior_period_forecast",
      etc: "gmn_etc",
      // complete: "gmn_complete",
      colType: "percentageColumn"
    },
    {
      row: "Net margin % Gross revenue",
      description: "Net margin / Gross revenue",
      prior_period_mtd: "nmgr_prior_period_mtd",
      mtd: "nmgr_mtd",
      ytd: "nmgr_ytd",
      itd: "nmgr_itd",
      original: "nmgr_original",
      approved: "nmgr_approved",
      forecast: "nmgr_forecast",
      prior_period_forecast: "nmgr_Prior_Period_Forecast",
      etc: "nmgr_etc",
      // complete: "nmgr_complete",
      colType: "percentageColumn"
    },
    {
      row: "Net margin % NSR",
      description: "Net margin / Net service revenue",
      prior_period_mtd: "nmn_prior_period_mtd",
      mtd: "nmn_mtd",
      ytd: "nmn_ytd",
      itd: "nmn_itd",
      original: "nmn_original",
      approved: "nmn_approved",
      forecast: "nmn_forecast",
      prior_period_forecast: "nmn_Prior_Period_Forecast",
      etc: "nmn_etc",
      // complete: "nmn_complete",
      colType: "percentageColumn"
    },
    {
      row: "Gain/Lost margin",
      description: "((Net margin / Gross revenue) - (Approved net margin budget/approved gross revenue budget))* YTD gross revenue. If >0 then Gain margin.  If <0 then Lost margin",
      prior_period_mtd: "glm_prior_period_mtd",
      mtd: "glm_mtd",
      ytd: "glm_ytd",
      itd: "glm_itd",
      // original: "glm_original",
      // approved: "glm_approved",
      // forecast: "glm_forecast",
      // prior_period_forecast: "glm_Prior_Period_Forecast",
      // etc: "glm_etc",
      // complete: "glm_complete",
      colType: "number2DecimalColumn"
    },
    {
      row: "Hours",
      description: "Total hours",
      prior_period_mtd: "hours_prior_period_mtd",
      mtd: "hours_mtd",
      ytd: "hours_ytd",
      itd: "hours_itd",
      original: "hours_original",
      approved: "hours_approved",
      forecast: "hours_forecast",
      prior_period_forecast: "hours_Prior_Period_Forecast",
      etc: "hours_etc",
      // complete: "hours_complete",
      colType: "number2DecimalColumn"
    },
    {
      row: "Avg. labor rate / hr",
      description: "Fully burdened labor / hours",
      prior_period_mtd: "alr_prior_period_mtd",
      mtd: "alr_mtd",
      ytd: "alr_ytd",
      itd: "alr_itd",
      original: "alr_original",
      approved: "alr_approved",
      forecast: "alr_forecast",
      prior_period_forecast: "alr_Prior_Period_Forecast",
      etc: "alr_etc",
      // complete: "alr_complete",
      colType: "number2DecimalColumn"
    },
    {
      row: "Direct labor multiplier (DLM)",
      description: "Net service revenue / Direct labor",
      prior_period_mtd: "dlm_prior_period_mtd",
      mtd: "dlm_mtd",
      ytd: "dlm_ytd",
      itd: "dlm_itd",
      original: "dlm_original",
      approved: "dlm_approved",
      forecast: "dlm_forecast",
      prior_period_forecast: "dlm_Prior_Period_Forecast",
      etc: "dlm_etc",
      // complete: "dlm_complete",
      colType: "number2DecimalColumn"
    },
    {
      row: "Salary cost multiplier (SCM)",
      description: "Net service revenue / (Direct labor + Fringe)",
      prior_period_mtd: "scm_prior_period_mtd",
      mtd: "scm_mtd",
      ytd: "scm_ytd",
      itd: "scm_itd",
      original: "scm_original",
      approved: "scm_approved",
      forecast: "scm_forecast",
      prior_period_forecast: "scm_Prior_Period_Forecast",
      etc: "scm_etc",
      // complete: "scm_complete",
      colType: "number2DecimalColumn"
    },
    {
      row: "Fringe % of direct labor",
      description: "Fringe cost / Direct labor",
      prior_period_mtd: "fdl_prior_period_mtd",
      mtd: "fdl_mtd",
      ytd: "fdl_ytd",
      itd: "fdl_itd",
      original: "fdl_original",
      approved: "fdl_approved",
      forecast: "fdl_forecast",
      prior_period_forecast: "fdl_Prior_Period_Forecast",
      etc: "fdl_etc",
      // complete: "fdl_complete",
      colType: "percentageColumn"
    },
    {
      row: "Overhead % of direct labor",
      description: "Applied overhead / Direct labor",
      prior_period_mtd: "odl_prior_period_mtd",
      mtd: "odl_mtd",
      ytd: "odl_ytd",
      itd: "odl_itd",
      original: "odl_original",
      approved: "odl_approved",
      forecast: "odl_forecast",
      prior_period_forecast: "odl_Prior_Period_Forecast",
      etc: "odl_etc",
      // complete: "odl_complete",
      colType: "percentageColumn"
    },
  ];